name: Build with maven

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_HOME: ~/.m2/repository
      MAVEN_OPTS: -Dmaven.repo.local=$MAVEN_HOME

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v1.0.3
        with:
          path: $MAVEN_HOME
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Compile with Maven
        run: mvn $MAVEN_OPTS -B clean compile

      - name: Test with Maven
        run: mvn $MAVEN_OPTS -B test

      - name: Package with Maven
        run: mvn $MAVEN_OPTS -B -DskipTests=true package

      - name: Test Coverage Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload app artifact
        uses: actions/upload-artifact@v2
        with:
          name: ci-cd-test.jar
          path: target/ci-cd-test-*.jar

      - name: Upload jacoco report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
